### ISSUE TITLE
Activating travis and coveralls

### ISSUE THREAD

**Issue by delijati** [Cornices/cornice.ext.swagger#1]
@leplatrem could you activate travis and coveralls for this repo

**Comment by leplatrem** [comment]
Travis looks ok:

![capture d ecran de 2016-11-02 16-22-18](https://cloud.githubusercontent.com/assets/546692/19934909/8e0c6b3a-a118-11e6-9f87-b2ef224d5f78.png)

But on coveralls, I can't see the repo :( Maybe @tarekziade can see it ?

**Comment by gabisurita** [comment]
That was solved. Thank you!
