### ISSUE TITLE
colander missing value not used as default

### ISSUE THREAD

**Issue by sp-schoen** [Cornices/cornice.ext.swagger#167]
In colander-SchemaNodes the missing-Parameter is there to set a default value for the de-serialization if the property is missing. The default-Option is only for serialization.
The behavior of cornice-swagger now is that the "default"-Value is used to fill the value in the swagger-ui (for a boolean). But it would be way more intuitive if the "missing"-Value would be used, because that is the default for de-serialization.

**Comment by leplatrem** [comment]
Thanks for reporting! 

Would you have some time to work on a pull-request for this fix?

**Comment by sp-schoen** [comment]
@leplatrem Yes, from looking at the code, it seems easy to fix this.

**Comment by sp-schoen** [comment]
@leplatrem #168
