### ISSUE TITLE
Document Swagger UI integration

### ISSUE THREAD

**Issue by gabisurita** [Cornices/cornice.ext.swagger#18]

**Comment by ergo** [comment]
I actually added a Swagger UI intergration in form of pyramid directive.

https://github.com/Cornices/cornice.ext.swagger/pull/79 - this PR adds this, along with tests and documentation changes to show how to enable the support, it is 100% backwards compatible.

**Comment by gabisurita** [comment]
Closed by #79.

**Comment by ergo** [comment]
Thanks @gabisurita.
