### ISSUE TITLE
Cookiecutter swagger demo

### ISSUE THREAD

**Issue by delijati** [Cornices/cornice.ext.swagger#2]
@leplatrem could you create a repo for my cookiecutter demo app `cookiecutter-cornice_swagger`

**Comment by delijati** [comment]
Added https://github.com/delijati/cookiecutter-cornice_swagger

**Comment by leplatrem** [comment]
Would you still need it or having it under your nickname is fine?

**Comment by delijati** [comment]
No it's fine i will try to maintain it.
