### ISSUE TITLE
Allow describing tags from decorators

### ISSUE THREAD

**Issue by gabisurita** [Cornices/cornice.ext.swagger#25]
Related to #23 

Maybe we could document tags from view and service definitions, like we do for responses.

Opinions?

**Comment by glasserc** [comment]
This sounds cleaner and more robust to me, but maybe slightly less convenient. If it were easy to implement some kind of Sphinx hook to pull information out of the docstrings "correctly", then maybe we could do that, but I don't think it's worth the amount of effort it would take.
